### PR TITLE
mermaid: Use stateDiagram-v2 to beautify state diagram.

### PR DESCRIPTION
**Pull request by YongHaoWu**

### CODE REVIEW

**Comment by maxekman** [comment]
Nice! Thanks.

Out of curiosity, could you provide a screenshot of the output result?

**Comment by YongHaoWu** [comment]
Sure, example of test file:
```
stateDiagram-v2
    [*] --> closed
    closed --> open: open
    intermediate --> closed: part-close
    open --> closed: close
```

pic is :
image

U can test it in https://mermaid-js.github.io/mermaid-live-editor/#/edit/dW5kZWZpbmVk

**Comment by YongHaoWu** [comment]
This is v1 staus:
image

while this is v2, it is much better: 
image

**Comment by maxekman** [comment]
Very nice! Thanks again!

**Pull request merged**
