### PR TITLE
Allow validating transitions without triggering event

### PR DESCRIPTION
**Pull request by alhails**
Hi,

Wanted the check for valid transitions to include the before callbacks - I think similar to suggestion in #10.
My changes break the existing interface for Can/Cannot so maybe not something that you would want to merge as it is, but any thoughts on whether you think this functionality would be useful and if so, what changes you would need to the PR before accepting?

Thanks

Alastair

### CODE REVIEW

**Comment by maxekman** [comment]
Hey, sorry for the delay. It looks like it could be useful, but as you say the simple Can/Cannot will have some added complexity. Do you have any suggestion for another name which would provide this functionality in addition to the simpler Can/Cannot?

**Comment by maxekman** [comment]
@alhails: Any more progress on this? Or should I close the PR?

**Comment by alhails** [comment]
@maxekman no further progress i'm afraid. happy for you to close PR if you don't see value in it.

**Comment by maxekman** [comment]
Closing due to inactivity.

**Pull request closed without merging**
