### PR TITLE
race fixes

### PR DESCRIPTION
**Pull request by eminden**

### CODE REVIEW

**Comment by maxekman** [comment]
Looks valuable, but could you shortly describe the issue and the solution? Thanks

**Comment by eminden** [comment]
Sorry for being late on the description, v1.0.0 is having data races, it can be clearly seen with the existing test cases when you run with -race flag, this pr solves the data races. 

Could you please push a new release after merging this pr if you are happy to do so?

**Comment by maxekman** [comment]
Thanks for the description! Would you mind adding the -race flag in this PR too? Just to catch stuff in the future.

I'll release a patch after this.

**Comment by eminden** [comment]
here it is.

**Comment by maxekman** [comment]
Thanks! There is unfortunately another location for CI (not optimal), would you mind updating here too?

https://github.com/looplab/fsm/blob/main/.github/workflows/main.yml#L21

**Comment by eminden** [comment]
sorry for missing that, it's ready now.

**Comment by maxekman** [comment]
@eminden Thanks for helping out! Here is the patch release: https://github.com/looplab/fsm/releases/tag/v1.0.1

**Pull request merged**
